#!/usr/bin/env python3
"""
7-Day Soak Test Script

This script simulates or schedules 7 consecutive daily runs of the pipeline
and provides a baseline comparison of metrics.

Usage:
    python3 scripts/soak_test.py [--mode {simulate,schedule}] [--days 7]

Modes:
    simulate: Run all days consecutively (default for testing)
    schedule: Create cron entries for actual scheduled runs
"""

import argparse
import json
import os
import sqlite3
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_SQLITE_PATH = "./data/daily-blog.db"
DEFAULT_REPORT_PATH = "./data/soak_test_report.json"
DEFAULT_CRON_TEMPLATE = """# Soak test cron entries - generated by scripts/soak_test.py
# Remove after soak test completes
PATH=/usr/local/bin:/usr/bin:/bin

{cron_entries}
"""


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def get_project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def run_single_pipeline() -> dict[str, Any]:
    """Run a single pipeline execution and return metrics."""
    project_root = get_project_root()
    pipeline_script = project_root / "run_pipeline.py"

    result = {
        "run_id": datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "timestamp": utc_now_iso(),
        "success": False,
        "returncode": None,
        "stdout": "",
        "stderr": "",
        "stages": {},
    }

    try:
        proc = subprocess.run(
            ["python3", str(pipeline_script)],
            capture_output=True,
            text=True,
            timeout=600,
            cwd=str(project_root),
        )
        result["returncode"] = proc.returncode
        result["success"] = proc.returncode == 0
        result["stdout"] = proc.stdout
        result["stderr"] = proc.stderr

        if result["success"]:
            # Extract metrics from database
            result["stages"] = extract_run_metrics(result["run_id"])

    except subprocess.TimeoutExpired as exc:
        result["stderr"] = f"Timeout: {exc}"
    except Exception as exc:
        result["stderr"] = f"Exception: {exc}"

    return result


def extract_run_metrics(run_id: str) -> dict[str, Any]:
    """Extract metrics from run_metrics table for a specific run."""
    sqlite_path = Path(os.getenv("SQLITE_PATH", DEFAULT_SQLITE_PATH))
    if not sqlite_path.exists():
        return {}

    conn = sqlite3.connect(sqlite_path)
    stages = {}

    try:
        rows = conn.execute(
            """
            SELECT stage_name, status, started_at, finished_at,
                   duration_ms, row_count, model_route_used, actual_model_used, error_message
            FROM run_metrics WHERE run_id = ?
            """,
            (run_id,),
        ).fetchall()

        for row in rows:
            stages[row[0]] = {
                "status": row[1],
                "started_at": row[2],
                "finished_at": row[3],
                "duration_ms": row[4],
                "row_count": row[5],
                "model_route_used": row[6],
                "actual_model_used": row[7],
                "error_message": row[8],
            }
    finally:
        conn.close()

    return stages


def get_historical_baseline(days: int = 7) -> dict[str, Any]:
    """Get baseline metrics from historical runs."""
    sqlite_path = Path(os.getenv("SQLITE_PATH", DEFAULT_SQLITE_PATH))
    if not sqlite_path.exists():
        return {}

    conn = sqlite3.connect(sqlite_path)
    baseline: dict[str, dict[str, Any]] = {}

    try:
        rows = conn.execute(
            """
            SELECT stage_name, status, AVG(duration_ms) as avg_duration_ms,
                   AVG(row_count) as avg_row_count, COUNT(*) as run_count
            FROM run_metrics
            WHERE started_at >= datetime('now', '-{} days')
            GROUP BY stage_name, status
            """.format(days * 2)
        ).fetchall()

        for row in rows:
            stage_name = row[0]
            status = row[1]
            if stage_name not in baseline:
                baseline[stage_name] = {}
            baseline[stage_name][status] = {
                "avg_duration_ms": row[2],
                "avg_row_count": row[3],
                "run_count": row[4],
            }
    finally:
        conn.close()

    return baseline


def compare_with_baseline(current_run: dict[str, Any], baseline: dict[str, Any]) -> dict[str, Any]:
    """Compare current run metrics with historical baseline."""
    comparison = {
        "baseline_analyzed": bool(baseline),
        "stages": {},
        "anomalies": [],
    }

    for stage_name, stage_metrics in current_run.get("stages", {}).items():
        if stage_name not in baseline:
            comparison["stages"][stage_name] = {"status": "no_baseline"}
            continue

        stage_baseline = baseline.get(stage_name, {})
        status_key = stage_metrics["status"]

        if status_key not in stage_baseline:
            comparison["stages"][stage_name] = {"status": "no_baseline"}
            continue

        baseline_data = stage_baseline[status_key]
        avg_duration = baseline_data.get("avg_duration_ms", 0)
        current_duration = stage_metrics.get("duration_ms", 0)

        duration_ratio = 0
        if avg_duration > 0:
            duration_ratio = current_duration / avg_duration

        comparison["stages"][stage_name] = {
            "baseline_avg_duration_ms": avg_duration,
            "current_duration_ms": current_duration,
            "duration_ratio": duration_ratio,
            "baseline_row_count": baseline_data.get("avg_row_count", 0),
            "current_row_count": stage_metrics.get("row_count", 0),
            "baseline_runs": baseline_data.get("run_count", 0),
        }

        # Flag anomalies
        if duration_ratio > 2.0:
            comparison["anomalies"].append(f"{stage_name}: duration {duration_ratio:.2f}x baseline")
        if duration_ratio < 0.5 and avg_duration > 0:
            comparison["anomalies"].append(
                f"{stage_name}: duration {duration_ratio:.2f}x baseline (unusually fast)"
            )

    return comparison


def generate_report(
    runs: list[dict[str, Any]],
    baseline: dict[str, Any],
    comparisons: list[dict[str, Any]],
) -> dict[str, Any]:
    """Generate a comprehensive soak test report."""
    total_runs = len(runs)
    successful_runs = sum(1 for r in runs if r.get("success", False))
    failed_runs = total_runs - successful_runs

    stage_stats: dict[str, dict[str, Any]] = {}
    all_anomalies: list[str] = []

    for run, comparison in zip(runs, comparisons):
        for anomaly in comparison.get("anomalies", []):
            all_anomalies.append(f"{run.get('run_id', 'unknown')}: {anomaly}")

        for stage_name, stage_data in run.get("stages", {}).items():
            if stage_name not in stage_stats:
                stage_stats[stage_name] = {
                    "total_runs": 0,
                    "successful_runs": 0,
                    "total_duration_ms": 0,
                }
            stage_stats[stage_name]["total_runs"] += 1
            if stage_data.get("status") == "ok":
                stage_stats[stage_name]["successful_runs"] += 1
            stage_stats[stage_name]["total_duration_ms"] += stage_data.get("duration_ms", 0)

    for stage_name, stats in stage_stats.items():
        if stats["total_runs"] > 0:
            stats["avg_duration_ms"] = stats["total_duration_ms"] // stats["total_runs"]
            stats["success_rate"] = (
                stats["successful_runs"] / stats["total_runs"] if stats["total_runs"] > 0 else 0
            )

    return {
        "soak_test_summary": {
            "total_runs": total_runs,
            "successful_runs": successful_runs,
            "failed_runs": failed_runs,
            "success_rate": successful_runs / total_runs if total_runs > 0 else 0,
            "start_time": runs[0].get("timestamp") if runs else None,
            "end_time": runs[-1].get("timestamp") if runs else None,
        },
        "stage_statistics": stage_stats,
        "all_anomalies": all_anomalies,
        "baseline_available": bool(baseline),
        "detailed_runs": runs,
        "comparisons": comparisons,
        "generated_at": utc_now_iso(),
    }


def create_cron_schedule(num_days: int) -> str:
    """Generate cron entries for scheduled soak test runs."""
    cron_entries = []
    for day in range(num_days):
        hour = 8 + day  # Stagger runs to avoid conflicts
        cron_entries.append(f"{hour} * * * * cd {get_project_root()} && python3 run_pipeline.py")

    return DEFAULT_CRON_TEMPLATE.format(cron_entries="\n".join(cron_entries))


def main() -> int:
    parser = argparse.ArgumentParser(description="7-Day Pipeline Soak Test")
    parser.add_argument(
        "--mode",
        choices=["simulate", "schedule"],
        default="simulate",
        help="Mode: simulate (run all days now) or schedule (create cron entries)",
    )
    parser.add_argument(
        "--days",
        type=int,
        default=7,
        help="Number of days to run (default: 7)",
    )
    parser.add_argument(
        "--report-path",
        default=DEFAULT_REPORT_PATH,
        help=f"Path to save report (default: {DEFAULT_REPORT_PATH})",
    )

    args = parser.parse_args()

    load_env_file(Path(".env"))

    print(f"=== {args.days}-Day Soak Test ===")
    print(f"Mode: {args.mode}")
    print(f"Report path: {args.report_path}")

    if args.mode == "schedule":
        print("\nGenerating cron schedule...")
        cron_content = create_cron_schedule(args.days)
        cron_path = Path("./ops/cron/soak_test.cron")
        cron_path.parent.mkdir(parents=True, exist_ok=True)
        cron_path.write_text(cron_content)
        print(f"Cron file created: {cron_path}")
        print("\nTo install (review first!):")
        print(f"  crontab {cron_path}")
        print("\nTo remove after test:")
        print("  crontab -e  # and remove the soak test entries")
        return 0

    # Simulate mode
    print("\nLoading historical baseline...")
    baseline = get_historical_baseline(days=args.days)
    print(f"Baseline stages: {list(baseline.keys())}")

    print(f"\nRunning {args.days} simulated pipeline executions...")
    runs: list[dict[str, Any]] = []
    comparisons: list[dict[str, Any]] = []

    for i in range(args.days):
        print(f"\n--- Day {i + 1}/{args.days} ---")
        run = run_single_pipeline()
        runs.append(run)

        if run["success"]:
            print(f"✓ Run {run['run_id']} completed successfully")
        else:
            print(f"✗ Run {run['run_id']} failed")

        comparison = compare_with_baseline(run, baseline)
        comparisons.append(comparison)

        if comparison["anomalies"]:
            print("Anomalies detected:")
            for anomaly in comparison["anomalies"]:
                print(f"  - {anomaly}")

    print("\nGenerating report...")
    report = generate_report(runs, baseline, comparisons)

    report_path = Path(args.report_path)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2))

    print(f"Report saved: {report_path}")

    # Print summary
    summary = report["soak_test_summary"]
    print("\n=== Summary ===")
    print(f"Total runs: {summary['total_runs']}")
    print(f"Successful: {summary['successful_runs']}")
    print(f"Failed: {summary['failed_runs']}")
    print(f"Success rate: {summary['success_rate']:.1%}")

    if report["all_anomalies"]:
        print(f"\n=== Anomalies ({len(report['all_anomalies'])}) ===")
        for anomaly in report["all_anomalies"][:20]:
            print(f"  - {anomaly}")

    print("\n=== Stage Statistics ===")
    for stage_name, stats in report["stage_statistics"].items():
        print(f"\n{stage_name}:")
        print(f"  Runs: {stats['total_runs']}/{stats['total_runs']}")
        print(f"  Success: {stats['successful_runs']} ({stats['success_rate']:.1%})")
        print(f"  Avg duration: {stats['avg_duration_ms']}ms")

    return 0 if summary["failed_runs"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
